---
addons:
  apt:
    packages:
      - tesseract-ocr
before_install:
  - "brew update"
  - "brew install https://raw.githubusercontent.com/Homebrew/homebrew/8ba134eda537d2cee7daa7ebdd9f728389d9c53e/Library/Formula/tesseract.rb"
before_script:
  - "bundle exec rake db:create RAILS_ENV=test"
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  api_key: ac2f23ae-49dc-46e5-bb29-8bd65ce12cc6
  app: projectze
  provider: heroku
  run:
    - bundle
    - "rake db:migrate"
  strategy: git
env:
  - DB=postgresql
language: ruby
rvm:
  - "2.0.0"
script:
  - "bundle exec rake spec"
